(ns build
  (:require [clojure.java.io :as io]
            [clojure.tools.build.api :as b]))

(def class-dir "target/classes")
;; Copied into the Dockerfile runtime stage by path — keep the two in step.
(def uber-file "target/app.jar")

;; Generated by scripts/build-css.sh, gitignored, and served at /css/app.css.
(def stylesheet "resources/public/css/app.css")

(defn- require-stylesheet!
  "The stylesheet is generated, so a clean checkout can build a jar that runs
  but renders unstyled. Refuse rather than ship that."
  []
  (when-not (.isFile (io/file stylesheet))
    (throw (ex-info (str "Missing " stylesheet " — run scripts/build-css.sh first.")
                    {:missing stylesheet}))))

(defn uber [_]
  (require-stylesheet!)
  (b/delete {:path "target"})
  (let [basis (b/create-basis {:project "deps.edn"})]
    ;; "resources" carries static assets, including the generated Tailwind
    ;; stylesheet (checked for above).
    (b/copy-dir {:src-dirs ["src" "resources"] :target-dir class-dir})
    (b/compile-clj {:basis basis :ns-compile '[books.server] :class-dir class-dir})
    (b/uber {:class-dir class-dir
             :uber-file uber-file
             :basis basis
             :main 'books.server})))
